/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tech_company;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class Assemployee extends javax.swing.JFrame {

    /**
     * Creates new form Assemployee
     */
    public Assemployee() {
        initComponents();
        DepartmentComboBox();
        DesignationComboBox2();
        //CDBTable();
    }

private void DepartmentComboBox() {
        DefaultComboBoxModel<String> model = (DefaultComboBoxModel<String>) jComboBox.getModel();

        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/tech_company", "root", "");
            String query = "SELECT DISTINCT dname FROM department"; 
            PreparedStatement pst = con.prepareStatement(query);
            ResultSet rs = pst.executeQuery();

            while (rs.next()) {
                String department = rs.getString("dname");
                model.addElement(department);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

private void DesignationComboBox2() {
        DefaultComboBoxModel<String> model = (DefaultComboBoxModel<String>) jComboBox2.getModel();

        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/tech_company", "root", "");
            String query = "SELECT DISTINCT desname FROM designations"; 
            PreparedStatement pst = con.prepareStatement(query);
            ResultSet rs = pst.executeQuery();

            while (rs.next()) {
                String rols = rs.getString("desname");
                model.addElement(rols);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        eid = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        epf = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jComboBox = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        fname = new javax.swing.JTextField();
        city = new javax.swing.JTextField();
        dob = new javax.swing.JTextField();
        lname = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        address = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        maleadd = new javax.swing.JRadioButton();
        femaleadd = new javax.swing.JRadioButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        eid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eidActionPerformed(evt);
            }
        });
        getContentPane().add(eid, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 250, 420, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("ID");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 250, 113, -1));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("EPF NO");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 290, 73, -1));
        getContentPane().add(epf, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 290, 420, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Gender");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 330, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Department");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 610, -1, -1));

        jComboBox.setEditable(true);
        jComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select" }));
        jComboBox.setInheritsPopupMenu(true);
        jComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 610, 420, -1));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 650, 420, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Desination");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 650, -1, -1));

        jButton1.setBackground(new java.awt.Color(102, 0, 102));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 740, -1, -1));

        jButton2.setBackground(new java.awt.Color(102, 0, 102));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Reset");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 740, 90, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("First Name");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 370, -1, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Last Name");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 410, -1, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("City");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 450, -1, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Date of Birth");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 490, -1, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Address");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 530, -1, -1));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Email");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 570, -1, -1));
        getContentPane().add(fname, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 370, 420, -1));
        getContentPane().add(city, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 450, 420, -1));
        getContentPane().add(dob, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 490, 420, -1));

        lname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lnameActionPerformed(evt);
            }
        });
        getContentPane().add(lname, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 410, 420, -1));
        getContentPane().add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 570, 420, -1));
        getContentPane().add(address, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 530, 420, -1));

        jButton3.setBackground(new java.awt.Color(102, 0, 102));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 740, 90, -1));

        jButton4.setBackground(new java.awt.Color(102, 0, 102));
        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Update");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 740, -1, -1));

        jButton5.setBackground(new java.awt.Color(102, 0, 102));
        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Search");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 200, 100, 30));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Employee Enrollment");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 100, 520, -1));

        maleadd.setBackground(new java.awt.Color(102, 0, 102));
        buttonGroup2.add(maleadd);
        maleadd.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        maleadd.setForeground(new java.awt.Color(255, 255, 255));
        maleadd.setText("Male");
        getContentPane().add(maleadd, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 330, -1, -1));

        femaleadd.setBackground(new java.awt.Color(102, 0, 102));
        buttonGroup2.add(femaleadd);
        femaleadd.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        femaleadd.setForeground(new java.awt.Color(255, 255, 255));
        femaleadd.setText("Female");
        getContentPane().add(femaleadd, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 330, -1, -1));

        jButton6.setBackground(new java.awt.Color(102, 0, 102));
        jButton6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("Delete");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 740, 90, -1));

        jButton7.setBackground(new java.awt.Color(102, 0, 102));
        jButton7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText("View Database");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 740, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/ccccccc.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 690, 110, 130));

        jButton8.setBackground(new java.awt.Color(102, 0, 102));
        jButton8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setText("Exit System");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 740, 130, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/aaaaaaaaaaaaaaaa.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 830));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxActionPerformed
        // combo:
        String selectedDepartment = (String) jComboBox.getSelectedItem();
        if (selectedDepartment != null) {

            System.out.println("Selected Department: " + selectedDepartment);
        }
    }//GEN-LAST:event_jComboBoxActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // comb2:
        String selectedRole = (String) jComboBox2.getSelectedItem();
        if (selectedRole != null) {

            System.out.println("Selected Role: " + selectedRole);
        }
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try {
        Class.forName("com.mysql.cj.jdbc.Driver");
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/tech_company", "root", "");
        String query = "INSERT INTO `employee`(`eid`,`epfno`,`gender`,`fname`,`lname`,`city`,`dob`,`address`,`email`,`department`,`designation`) VALUES (?,?,?,?,?,?,?,?,?,?,?)";
        PreparedStatement pst = con.prepareStatement(query);
        pst.setString(1, eid.getText());
        pst.setString(2, epf.getText());
        
        // Radio button group for gender selection
        if (maleadd.isSelected()) {
            pst.setString(3, "Male");
        } else if (femaleadd.isSelected()) {
            pst.setString(3, "Female");
        } else {
            pst.setString(3, ""); // Set it to null if none is selected
        }
        
        pst.setString(4, fname.getText());
        pst.setString(5, lname.getText());
        pst.setString(6, city.getText());
        pst.setString(7, dob.getText());
        pst.setString(8, address.getText());
        pst.setString(9, email.getText());
        pst.setString(10, (String) jComboBox.getSelectedItem()); // Selected department
        pst.setString(11, (String) jComboBox2.getSelectedItem()); // Selected designation

        pst.executeUpdate();
        JOptionPane.showMessageDialog(this, "Employee Added");

        // Clear the radio button selection
        buttonGroup2.clearSelection();

        eid.setText(null);
        epf.setText(null);
        fname.setText(null);
        lname.setText(null);
        city.setText(null);
        dob.setText(null);
        address.setText(null);
        email.setText(null);
        jComboBox.setSelectedIndex(0);
        jComboBox2.setSelectedIndex(0);
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, e);
    }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        try {
        Class.forName("com.mysql.jdbc.Driver");
        Connection con = java.sql.DriverManager.getConnection("jdbc:mysql://localhost:3306/tech_company", "root", "");
        String query = "UPDATE `employee` SET `epfno`=?, `gender`=?, `fname`=?, `lname`=?, `city`=?, `dob`=?, `address`=?, `email`=?, `department`=?, `designation`=? WHERE `eid`=?";
        PreparedStatement pst = con.prepareStatement(query);
        pst.setString(1, epf.getText());

        // Radio button group for gender selection
        if (maleadd.isSelected()) {
            pst.setString(2, "Male");
        } else if (femaleadd.isSelected()) {
            pst.setString(2, "Female");
        } else {
            pst.setString(2, ""); // Set it to null if none is selected
        }

        pst.setString(3, fname.getText());
        pst.setString(4, lname.getText());
        pst.setString(5, city.getText());
        pst.setString(6, dob.getText());
        pst.setString(7, address.getText());
        pst.setString(8, email.getText());
        pst.setString(9, (String) jComboBox.getSelectedItem()); // Selected department
        pst.setString(10, (String) jComboBox2.getSelectedItem()); // Selected designation
        pst.setString(11, eid.getText()); // Employee ID for updating

        pst.executeUpdate();
        javax.swing.JOptionPane.showMessageDialog(this, "Details Updated");

        // Clear the input fields and reset the radio buttons
        eid.setText(null);
        epf.setText(null);
        buttonGroup2.clearSelection();
        fname.setText(null);
        lname.setText(null);
        city.setText(null);
        dob.setText(null);
        address.setText(null);
        email.setText(null);
        jComboBox.setSelectedIndex(0);
        jComboBox2.setSelectedIndex(0);

        eid.requestFocus(); // Set focus back to the Employee ID field
    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(null, e);
    }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void lnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lnameActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        try {
        Class.forName("com.mysql.cj.jdbc.Driver");
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/tech_company", "root", "");
        String searchQuery = eid.getText(); 

        String query = "SELECT * FROM `employee` WHERE `eid` = ?";
        PreparedStatement pst = con.prepareStatement(query);
        pst.setString(1, searchQuery);

        ResultSet rs = pst.executeQuery();

        if (rs.next()) {
            // Display the search results in the relevant fields
            String employeeId = rs.getString("eid");
            String epfNo = rs.getString("epfno");
            String gender = rs.getString("gender");
            String firstName = rs.getString("fname");
            String lastName = rs.getString("lname");
            String cityValue = rs.getString("city");
            String dateOfBirth = rs.getString("dob");
            String addressValue = rs.getString("address");
            String emailValue = rs.getString("email");
            String departmentValue = rs.getString("department");
            String designationValue = rs.getString("designation");
        
            JOptionPane.showMessageDialog(this, "Serach Successful");

            eid.setText(employeeId);
            epf.setText(epfNo);

            // Set the gender radio button based on the search result
            if (gender.equals("Male")) {
                maleadd.setSelected(true);
            } else if (gender.equals("Female")) {
                femaleadd.setSelected(true);
            } else {
                buttonGroup2.clearSelection(); // Clear selection if gender is not specified
            }

            fname.setText(firstName);
            lname.setText(lastName);
            city.setText(cityValue);
            dob.setText(dateOfBirth);
            address.setText(addressValue);
            email.setText(emailValue);

            // Set the selected values in the combo boxes
            jComboBox.setSelectedItem(departmentValue);
            jComboBox2.setSelectedItem(designationValue);
        } else {
            JOptionPane.showMessageDialog(this, "No matching record found.");
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, e);
    }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        try {
        Class.forName("com.mysql.cj.jdbc.Driver");
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/tech_company", "root", "");
        String employeeId = eid.getText(); 

        // Verify if the employee with the given eid exists
        String verifyQuery = "SELECT * FROM `employee` WHERE `eid` = ?";
        PreparedStatement verifyPst = con.prepareStatement(verifyQuery);
        verifyPst.setString(1, employeeId);

        ResultSet verifyRs = verifyPst.executeQuery();

        if (verifyRs.next()) {
            // Employee with the given eid exists, proceed with the delete
            String deleteQuery = "DELETE FROM `employee` WHERE `eid`=?";
            PreparedStatement pst = con.prepareStatement(deleteQuery);
            pst.setString(1, employeeId);

            int result = pst.executeUpdate();
            
            if (result > 0) {
                JOptionPane.showMessageDialog(this, "Employee Details Deleted");
                // Clear the input fields and reset radio buttons
                eid.setText(null);
                epf.setText(null);
                buttonGroup2.clearSelection();
                fname.setText(null);
                lname.setText(null);
                city.setText(null);
                dob.setText(null);
                address.setText(null);
                email.setText(null);
                jComboBox.setSelectedIndex(0);
                jComboBox2.setSelectedIndex(0);
            } else {
                JOptionPane.showMessageDialog(this, "Failed to delete employee details");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Employee with the provided ID does not exist.");
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, e);
    }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        eid.setText(null);
        epf.setText(null);
        buttonGroup2.clearSelection(); // Clear the radio buttons in buttonGroup2
        fname.setText(null);
        lname.setText(null);
        city.setText(null);
        dob.setText(null);
        address.setText(null);
        email.setText(null);
        jComboBox.setSelectedIndex(0); 
        jComboBox2.setSelectedIndex(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        Viewemployeetb vdb = new Viewemployeetb();
        vdb.show();
        this.hide();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void eidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eidActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        JFrame frame = new JFrame("EXIT");
        if(JOptionPane.showConfirmDialog(frame,"Conform if you want to Exit","Exit",
            JOptionPane.YES_NO_OPTION)==JOptionPane.YES_NO_OPTION)
    {
        System.exit(0);
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        mainmanu homeobj = new mainmanu();
        homeobj.show();
        this.hide();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Assemployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Assemployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Assemployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Assemployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Assemployee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField address;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JTextField city;
    private javax.swing.JTextField dob;
    private javax.swing.JTextField eid;
    private javax.swing.JTextField email;
    private javax.swing.JTextField epf;
    private javax.swing.JRadioButton femaleadd;
    private javax.swing.JTextField fname;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JComboBox<String> jComboBox;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField lname;
    private javax.swing.JRadioButton maleadd;
    // End of variables declaration//GEN-END:variables
}
